import type { Creator, SignalRecord } from "./contracts";

export const demoCreators: Creator[] = [
  {
    id: "creator-field-notes",
    name: "Field Notes Studio",
    handle: "@fieldnotesstudio",
    network: "youtube",
    audience: 84200,
    accent: "#ff6546",
  },
  {
    id: "creator-practical-futures",
    name: "Practical Futures",
    handle: "@practicalfutures",
    network: "youtube",
    audience: 137000,
    accent: "#2c6e62",
  },
  {
    id: "creator-studio-index",
    name: "Studio Index",
    handle: "@studioindex",
    network: "instagram",
    audience: 56900,
    accent: "#59645f",
  },
  {
    id: "creator-useful-machines",
    name: "Useful Machines",
    handle: "@usefulmachines",
    network: "tiktok",
    audience: 211000,
    accent: "#be533d",
  },
];

export const demoSignals: SignalRecord[] = [
  {
    id: "signal-briefs",
    creatorId: "creator-field-notes",
    title: "The five-minute brief that stops revision loops",
    publishedAt: "2026-08-21T14:20:00.000Z",
    views: 184000,
    likes: 12900,
    comments: 884,
    durationSeconds: 522,
    thumbnailSeed: "brief-workshop",
    topic: "creative operations",
  },
  {
    id: "signal-agents",
    creatorId: "creator-practical-futures",
    title: "I gave one agent a real operating budget",
    publishedAt: "2026-08-20T10:00:00.000Z",
    views: 426000,
    likes: 31800,
    comments: 1430,
    durationSeconds: 688,
    thumbnailSeed: "agent-budget",
    topic: "agent workflows",
  },
  {
    id: "signal-thumbnail",
    creatorId: "creator-studio-index",
    title: "Why quiet thumbnails are winning again",
    publishedAt: "2026-08-19T18:45:00.000Z",
    views: 91600,
    likes: 8500,
    comments: 506,
    durationSeconds: 74,
    thumbnailSeed: "quiet-thumbnail",
    topic: "packaging",
  },
  {
    id: "signal-memory",
    creatorId: "creator-useful-machines",
    title: "A memory layer you can inspect with plain text",
    publishedAt: "2026-08-18T09:15:00.000Z",
    views: 792000,
    likes: 66700,
    comments: 2204,
    durationSeconds: 141,
    thumbnailSeed: "plain-text-memory",
    topic: "agent workflows",
  },
  {
    id: "signal-format",
    creatorId: "creator-field-notes",
    title: "The teardown format that earns saves",
    publishedAt: "2026-08-16T16:30:00.000Z",
    views: 103000,
    likes: 9800,
    comments: 611,
    durationSeconds: 417,
    thumbnailSeed: "format-teardown",
    topic: "content formats",
  },
  {
    id: "signal-research",
    creatorId: "creator-practical-futures",
    title: "Research systems should show their receipts",
    publishedAt: "2026-08-14T11:05:00.000Z",
    views: 171000,
    likes: 11400,
    comments: 730,
    durationSeconds: 603,
    thumbnailSeed: "research-receipts",
    topic: "evidence systems",
  },
];

export const demoIdeas = [
  {
    id: "idea-1",
    title: "The agent workflow nobody documents",
    format: "Evidence-led teardown",
    evidence: 3,
    state: "Ready to brief",
  },
  {
    id: "idea-2",
    title: "Why visible receipts build AI trust",
    format: "Contrarian explainer",
    evidence: 2,
    state: "Needs one example",
  },
  {
    id: "idea-3",
    title: "The small-team operating system",
    format: "Field guide",
    evidence: 4,
    state: "Drafting",
  },
];
